config/routes.rb
Rails.application.routes.draw do
  root to: "users#landing"

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  

  resources :posts do
    resources :signups, only: [:create]
  end
  resources :users, only: [:show, :create, :edit, :update, :index] do
    member do
      post 'Follow'
      post 'Unfollow'  
      get '/timeline', to: 'users#timeline'              
    end
    resources :relationships, only: [:create, :destroy, :index]  
  end
  resources :password_resets
  resources :categories
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "leader_id", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :leader_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :leader_relationships, source: :leader 

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
  before_create { generate_token(:auth_token) }

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator?'
  end

  def feed
    following_ids = "SELECT leader_id FROM relationships
                     WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id) # Produces feeds for timeline
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :timeline]
  before_action :require_same_user, only: [:edit, :update]    

  def show
    @posts = current_user.posts.paginate(:page => params[:page], :per_page => 30) 
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 30)  
  end

  def timeline
    @posts = @user.feed.paginate(:page => params[:page], :per_page => 30) 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You're registered."
      redirect_to root_path
    else
      render :new
      flash[:notice] = "Username or email taken."
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :id)
  end

  def set_user  
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You're not allowed to do that."
      redirect_to root_path
    end
  end
end

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Edit Your Details</h1>
  </div>
  <div class="panel-body">
    <%= form_for @user do |f| %>
      <div class='form-group'>
        <%= f.label :username %>
        <%= f.text_field :username, placeholder: "A name that puts a smile on your face.", class: "form-control" %>
      </div>
      <div class='form-group'>
        <%= f.label :email %>
        <%= f.text_field :email, placeholder: "An email you often use.", class: "form-control" %>
      </div>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "A reminder that touches your heart.", class: "form-control" %>
      </div>
      <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class='span8 well'>
    <p>
      <%= link_to user.username, user_path(user) %> 
    </p>
    <p>
  <% if logged_in? %>
    <% if !current_user.followings.include?(user) %>
      <%= link_to "Follow", user_relationships_path(user), method: 'post' %>
    <% else %>   
      <%= link_to "UnFollow", user_relationship_path(user, current_user), method: 'delete' %>
    <% end %>
  <% end %>
</p>
  </div>
<% end %>

<%= render 'shared/will_paginate' %>

app/views/users/landing.html.erb
<% if logged_in? %>
  <div class ="text-center">
    <h1>Hello, world!</h1>
  </div>
<% else %>
  <div class ="text-center">
    <h1>Hello, world!</h1>
    <p><%= link_to 'Register', register_path, class: 'btn btn-success btn-lg' %>
    <%= link_to 'Log in', login_path, class: 'btn btn-warning btn-lg' %></p>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Register</h1>
  </div>
  <div class="panel-body">
    <%= form_for @user do |f| %>
      <div class='form-group'>
        <%= f.label :username %>
        <%= f.text_field :username, placeholder: "A name that puts a smile on your face.", class: "form-control" %>
      </div>
      <div class='form-group'>
        <%= f.label :email %>
        <%= f.text_field :email, placeholder: "An email you often use.", class: "form-control" %>
      </div>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "A reminder that touches your heart.", class: "form-control" %>
      </div>
      <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Profile</h2>

<p>
  <% if logged_in? && @user != current_user %>
    <% if !current_user.followings.include?(@user) %>
      <%= link_to "Follow", user_relationships_path(@user), method: 'post' %>
    <% else %>   
      <%= link_to "Share", user_relationship_path(@user, current_user) %> | 
      <%= link_to "Unfollow", user_relationship_path(@user, current_user), method: 'delete' %>
    <% end %>
  <% else %>
  <% end %>
</p>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

<%= render 'shared/will_paginate' %>

app/views/users/timeline.html.erb
<h2><%= @user.username %>'s Timeline</h2>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

<%= render 'shared/will_paginate' %>