config/routes.rb
Rails.application.routes.draw do
  root to: "users#landing"

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  

  resources :posts do
    resources :signups, only: [:create]
  end
  resources :users, only: [:show, :create, :edit, :update, :index] do
    member do
      post 'Follow'
      post 'Unfollow'  
      get '/timeline', to: 'users#timeline'              
    end
    resources :relationships, only: [:create, :destroy, :index]  
  end
  resources :password_resets
  resources :categories
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :bounties, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories, dependent: :destroy
  validates :description, presence: true
  accepts_nested_attributes_for :bounties, :reject_if => :all_blank, :allow_destroy => true
  self.per_page = 10
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 30)
  end

  def show
    @signup = Signup.new
    @bounty = @post.bounties.all
  end

  def new
    @post = Post.new
    @bounty = Bounty.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end
  end 

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit( :description, :category_ids, bounties_attributes: [:title, :description, :_destroy])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/views/posts/_bounty_fields.html.erb
<div class="control-group nested-fields well">
  <div class="form-group">
    <%= f.label "Bounty Title" %>
    </br>
    <%= f.text_field :title, class: "form-control" %>
  </div>    
  <div class="form-group">
    <%= f.label "Description" %>
    </br>
    <%= f.text_area :description, class: "form-control" %>    
  </div>
    <%= link_to_remove_association "remove", f %>
</div>

app/views/posts/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Create New Project</h1>
  </div>
    <div class="panel-body">
      <%= form_for @post do |f| %>
        <div class='form-group'>
          <%= f.label "Share your project with us." %>
          <%= f.text_area :description, rows: 5, class: "form-control" %>
        </div>
        <div class='form-group'>
          <%= f.label "Categories" %>
          <%= f.collection_select :category_ids, Category.order(:name), :id, :name, include_blank: true %>   
        </div>
        <div class='form-group'>
          <fieldset id="post-bounties">      
              <%= f.fields_for :bounties do |bounty| %>
                <%= render 'bounty_fields', f: bounty %>
              <% end %>       
            <%= link_to_add_association 'Add Bounty!', f, :bounties %>
          </fieldset>                                     
        </div>          
        <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-success')%>
      <% end %>
    </div>
</div>

app/views/posts/_form_edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Create New Project</h1>
  </div>
    <div class="panel-body">
      <%= form_for @post do |f| %>
        <div class='form-group'>
          <%= f.label "Share your project with us." %>
          <%= f.text_area :description, rows: 5, class: "form-control" %>
        </div>
        <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-success')%>
      <% end %>
    </div>
</div>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>">
  <small class='quiet text-left'> On <%= display_datetime(post.created_at) %></small>  
  </br>
  </br>
  <div class="well">
    <p>
      <%= render post.categories %>
    </p>
    <p>
      <%= link_to post.description, post_path(post) %>
    </p>
    <footer>
      <span class='quiet'>
        status by
        <%= link_to post.creator.username, user_path(post.creator) %>
      </span>   
    </footer>
  </div> 
  <hr>  
  </br>  
</div>

app/views/posts/edit.html.erb
<%= render 'form_edit' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<%= render 'shared/will_paginate' %>

app/views/posts/show.html.erb
<% if logged_in? and (current_user == @post.creator) %>
  <%= link_to "Edit Post", edit_post_path(@post) %>
<% end %>   
<div class="row">
  <div class="col-xs-12 col-md-8">
    <div id="post-<%= @post.id %>">
      <small class='quiet text-left'> On <%= display_datetime(@post.created_at) %></small>
      </br>
      </br>
        <p>
          <%= @post.description %>
        </p>
        <footer>
          <span class='quiet'>
            status by
            <%= link_to @post.creator.username, user_path(@post.creator) %>
          </span> 
        </footer>  
      <hr>
      </br>  
    </div>
    <% if logged_in? %>
      <%= form_for [@post, @signup] do |f| %>
        <%= f.hidden_field :username, :value => "#{current_user.username}" %>
        <%= f.hidden_field :email, :value => "#{current_user.email}" %>
        <%= f.submit "Sign up with your username and email by clicking this button.", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-6 col-md-4">
    <div class="well">
      <% @bounty.each do |bounty| %>
        <p>
        <%= bounty.title %>
        </p>
        <p>
        <%= bounty.description %>
        </p>
      <% end %>
    </div>   
  </div>
</div>