config/routes.rb
Rails.application.routes.draw do
  root to: "users#landing"

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  

  resources :posts do
    resources :signups, only: [:create]
  end
  resources :users, only: [:show, :create, :edit, :update, :index] do
    member do
      post 'Follow'
      post 'Unfollow'  
      get '/timeline', to: 'users#timeline'              
    end
    resources :relationships, only: [:create, :destroy, :index]  
  end
  resources :password_resets
  resources :categories
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
  <div class="container-fluid">
    <div class='navbar-header'>
        <%= link_to "Affiliation", posts_path, class: 'navbar-brand'  %>
    </div>      
      <div class="nav navbar-header navbar-right">       
        <div class='btn btn-group nav_item'>
          <%= link_to('', class: 'btn btn-default dropdown-toggle', 'data-toggle' => 'dropdown') do %>
            Click On: <strong><%= current_user.username %></strong>
            <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu'>
            <li>
              <%= link_to user_path(current_user) do %>
                View Profile
              <% end %>
            </li>  
            <li>
              <%= link_to timeline_user_path(current_user) do %>
                View Timeline
              <% end %>
            </li>            
            <li>
              <%= link_to edit_user_path(current_user) do %>
                Edit Profile
              <% end %>
            </li>    
            <li>
              <%= link_to new_category_path do %>
                New Category
              <% end %>
            </li>                                  
            <li>
              <%= link_to new_post_path do %>
                New Post
              <% end %>
            </li>        
            <li>
              <%= link_to logout_path do %>
                <i class='icon-circle-arrow-left'></i>
                Log Out
              <% end %>
            </li>
          </ul>
        </div>
      </div>    
      <% else # logged out%>
      <div class="container-fluid">
        <div class='navbar-header'>
            <%= link_to "Affiliation", root_path, class: 'navbar-brand'  %>
        </div>        
        <div class="nav navbar-header navbar-right">
          <div class='nav_item'>
            <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
          </div>
          <div class='nav_item'>
            <%= link_to 'Log in', login_path, class: 'btn btn-warning btn-small' %>
          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Affiliation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="navbar">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
  </header>
  <div id="main" role="main">  
      <div class="container">
        <div class="row">
          <div class="span12">    
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    <footer>
    </footer>      
  </div>
</body>
</html>